apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tic-tac-toe
stringData:
  MYSQL_ROOT_PASSWORD: "StrongPassword123"
  MYSQL_DATABASE: "tic_tac_toe_db"
  MYSQL_USER: "tictactoe_user"
  MYSQL_PASSWORD: "StrongPassword123"